const movieArray = [
    { 
        id: 0,  
        title: "Cocaine Bear", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//gOnmaxHo0412UVr1QM5Nekv1xPi.jpg", 
          releaseDate: "2023-02-22", 
          overview: "Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.", 
          rating: "6.6",
       }, 
       { 
        id: 1,
          title: "The Whale", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg", 
          releaseDate: "2022-12-09", 
          overview: "A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.", 
          rating: "8.1", 
      }, 
      { 
        id: 2,
          title: "Everything Everywhere All at Once", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg", 
          releaseDate: "2022-03-24", 
          overview: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.", 
          rating: "7.9", 
      }, 
      { 
        id: 3,
          title: "A Man Called Otto", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//130H1gap9lFfiTF9iDrqNIkFvC9.jpg", 
          releaseDate: "2022-12-28", 
          overview: "When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.", 
          rating: "7.9",
       }, 
       { 
        id: 4,
          title: "M3GAN", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//d9nBoowhjiiYc4FBNtQkPY7c11H.jpg", 
          releaseDate: "2022-12-28", 
          overview: "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.", 
          rating: 7.4, 
      }, 
      {
        id: 5,
          title: "Scream VI", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//aePBN8ffLCHoUXp8lkA5P29CXdx.jpg", 
          releaseDate: "2023-03-08", 
          overview: "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.", 
          rating: "7.4", 
      }, 
      { 
        id: 6,
          title: "Smile", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg", 
          releaseDate: "2022-09-23", 
          overview: "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.", 
          rating: "6.8", 
      }, 
      { 
        id: 7,
          title: "80 for Brady", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//jixBLmH4gQuTKTenZr89egvqZbW.jpg", 
          releaseDate: "2023-02-03", 
          overview: "A quartet of elderly best friends decide to live life to the fullest by taking a wild trip to the Super Bowl LI to see their hero Tom Brady play.", 
          rating: "7.2", 
      }, 
      { 
        id: 7,
          title: "Top Gun: Maverick", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//62HCnUTziyWcpDaBO2i1DX17ljH.jpg", 
          releaseDate: "2022-05-24", 
          overview: "After more than thirty years of service as one of the Navy\'s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.", 
          rating: "8.3", 
      }, 
      { 
        id: 8,
          title: "Elvis", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg", 
          releaseDate: "2022-06-22", 
          overview: "The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.", 
          rating: "7.7",
       }, 
       { 
        id: 9,
          title: "Black Panther: Wakanda Forever", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//sv1xJUazXeYqALzczSZ3O6nkH75.jpg", 
          releaseDate: "2022-11-09", 
          overview: "Queen Ramonda, Shuri, M\'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T\'Challa\'s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.", 
          rating: "7.3", 
      }, 
      { 
        id: 10,
          title: "Oppenheimer", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//bAFmcrCpXsJis5q0aaXvCz3dTiX.jpg", 
          releaseDate: "2023-07-19", 
          overview: "The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II.", 
          rating: "0", 
      }, 
      { 
        id: 11,
          title: "Mission: Impossible - Dead Reckoning Part One", 
          posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//pZCa8WgnP0AgVHsFjvuUDhcNjOJ.jpg", 
          releaseDate: "2023-07-12", 
          overview: "The seventh installment of the Mission: Impossible franchise.",
          rating: "0", 
        }, 
          { 
            id: 12,
              title: "Spider-Man: Across the Spider-Verse", 
              posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//zknrogDlwcmaz3yHkA3yEhy005t.jpg", 
              releaseDate: "2023-05-31", 
              overview: "After reuniting with Gwen Stacy, Miles Morales — Brooklyn's full-time, friendly neighborhood Spider-Man — is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must redefine what it means to be a hero so he can save the people he loves most.", 
              rating: 0, 
          }, 
          { 
            id: 13,
              title: "Indiana Jones and the Dial of Destiny", 
              posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//y4MBS0SKE0pHR57vfYBxGhrkfcv.jpg", 
              releaseDate: "2023-06-28", 
              overview: "Finding himself in a new era, approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.", 
              rating: "0", 
          }, 
          { 
            id: 14,
              title: "Joker: Folie à Deux", 
              posterURL: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/78d92c45-e7d3-4e39-943e-6a11a8c60778/dfamc79-ec20ff3b-c786-4116-95df-37d3ca59ae21.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzc4ZDkyYzQ1LWU3ZDMtNGUzOS05NDNlLTZhMTFhOGM2MDc3OFwvZGZhbWM3OS1lYzIwZmYzYi1jNzg2LTQxMTYtOTVkZi0zN2QzY2E1OWFlMjEuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.OHf_2rkP4WxxW0VU2LzYxJuqrik670WP9uUBM_HtVtc", 
              releaseDate: "2024-10-02", 
              overview: "A sequel to the 2019 film Joker.", 
              rating: "0", 
          }, 
          { 
            id: 15,
              title: "Guardians of the Galaxy Volume 3", 
              posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//4zdyTce32M3uKU8gS31d4ZsmNhQ.jpg", 
              releaseDate: "2023-05-03", 
              overview: "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.", 
              rating: "0", 
          }, 
          { 
            id: 16,
              title: "The Little Mermaid", 
              posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg", 
              releaseDate: "2023-05-24", 
              overview: "The youngest of King Triton's daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life and her father's crown in jeopardy.", 
              rating: "0", 
          }, 
          { 
            id: 17,
                  title: "Barbie", 
                  posterURL: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2//xMVsBwvvw1iKhC97rtI5mB91C0O.jpg", 
                  releaseDate: "2023-07-19", 
                  overview: "Live-action feature film based on the popular line of Barbie dolls.", 
                  rating: "0", 
              }
    ];

    export default movieArray;